version: '3.3'
services:
  train_php:
    build: ./
    ports:
      - "80:80"
    links:
      - train_mysql
    volumes:
      - .:/var/www/html
    container_name: train_php
    tty: true
    extra_hosts:
      - "www.trainning.test: 127.0.0.1"
  train_mysql:
    image: mysql:5.6
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: train
      MYSQL_USER: train
      MYSQL_PASSWORD: train
      MYSQL_DATABASE: train
    container_name: train_mysql
  train_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: train
      PMA_HOST: train_mysql
      PMA_USER: train
      PMA_PASSWORD: train
    ports:
      - "8080:80"
    links:
      - train_mysql
    container_name: train_phpmyadmin
