<?php
/** @var $this Powerbody_Slider_Block_Widget_Slider */
$bgImages = $this->getBgImagesOfGroup();
?>

<div class="slideshow-container">
    <?php foreach ($bgImages as $bgImage) : ?>
        <div class="mySlides fade">
            <div class="numbertext"></div>
            <img src="media/slider/<?php echo $bgImage; ?>" style="width:100%;">
            <div class="text"></div>
        </div>
    <?php endforeach; ?>
</div>
<br>
<div style="text-align:center">
    <?php foreach ($bgImages as $bgImage) : ?>
        <span class="dot"></span>
    <?php endforeach; ?>
</div>

<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) {
            slideIndex = 1
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
        setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
</script>
